//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonTerms {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonTerms() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Api.Resources.CommonTerms", typeof(CommonTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Action_Process {
            get {
                return ResourceManager.GetString("Action_Process", resourceCulture);
            }
        }
        
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        public static string Common_Status {
            get {
                return ResourceManager.GetString("Common_Status", resourceCulture);
            }
        }
        
        public static string Common_Vegan {
            get {
                return ResourceManager.GetString("Common_Vegan", resourceCulture);
            }
        }
        
        public static string Error_Ingredient_In_Use {
            get {
                return ResourceManager.GetString("Error_Ingredient_In_Use", resourceCulture);
            }
        }
        
        public static string Error_ProductCategory_In_Use {
            get {
                return ResourceManager.GetString("Error_ProductCategory_In_Use", resourceCulture);
            }
        }
        
        public static string Home_Index {
            get {
                return ResourceManager.GetString("Home_Index", resourceCulture);
            }
        }
        
        public static string Ingredient_Create {
            get {
                return ResourceManager.GetString("Ingredient_Create", resourceCulture);
            }
        }
        
        public static string Ingredient_Index {
            get {
                return ResourceManager.GetString("Ingredient_Index", resourceCulture);
            }
        }
        
        public static string ProductActivities_Index {
            get {
                return ResourceManager.GetString("ProductActivities_Index", resourceCulture);
            }
        }
        
        public static string Product_Index {
            get {
                return ResourceManager.GetString("Product_Index", resourceCulture);
            }
        }
        
        public static string Product_Workload {
            get {
                return ResourceManager.GetString("Product_Workload", resourceCulture);
            }
        }
        
        public static string ProductCategory_Create {
            get {
                return ResourceManager.GetString("ProductCategory_Create", resourceCulture);
            }
        }
        
        public static string ProductCategory_Index {
            get {
                return ResourceManager.GetString("ProductCategory_Index", resourceCulture);
            }
        }
    }
}
