//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainTerms {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainTerms() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Model.Resources.DomainTerms", typeof(DomainTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Ingredient_AllergyKeywords {
            get {
                return ResourceManager.GetString("Ingredient_AllergyKeywords", resourceCulture);
            }
        }
        
        public static string Ingredient_Keywords {
            get {
                return ResourceManager.GetString("Ingredient_Keywords", resourceCulture);
            }
        }
        
        public static string Ingredient_Name {
            get {
                return ResourceManager.GetString("Ingredient_Name", resourceCulture);
            }
        }
        
        public static string Ingredient_NeedsReview {
            get {
                return ResourceManager.GetString("Ingredient_NeedsReview", resourceCulture);
            }
        }
        
        public static string Ingredient_VeganType {
            get {
                return ResourceManager.GetString("Ingredient_VeganType", resourceCulture);
            }
        }
        
        public static string Product_ProductActivities {
            get {
                return ResourceManager.GetString("Product_ProductActivities", resourceCulture);
            }
        }
        
        public static string Product_AllergyInfo {
            get {
                return ResourceManager.GetString("Product_AllergyInfo", resourceCulture);
            }
        }
        
        public static string Product_Ingredients {
            get {
                return ResourceManager.GetString("Product_Ingredients", resourceCulture);
            }
        }
        
        public static string Product_IsManufacturerAdvertisedVegan {
            get {
                return ResourceManager.GetString("Product_IsManufacturerAdvertisedVegan", resourceCulture);
            }
        }
        
        public static string Product_IsProcessed {
            get {
                return ResourceManager.GetString("Product_IsProcessed", resourceCulture);
            }
        }
        
        public static string Product_MatchedIngredients {
            get {
                return ResourceManager.GetString("Product_MatchedIngredients", resourceCulture);
            }
        }
        
        public static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        public static string Product_ProductCategories {
            get {
                return ResourceManager.GetString("Product_ProductCategories", resourceCulture);
            }
        }
        
        public static string Product_VeganDescription {
            get {
                return ResourceManager.GetString("Product_VeganDescription", resourceCulture);
            }
        }
        
        public static string Product_VeganType {
            get {
                return ResourceManager.GetString("Product_VeganType", resourceCulture);
            }
        }
        
        public static string Product_WorkloadItems {
            get {
                return ResourceManager.GetString("Product_WorkloadItems", resourceCulture);
            }
        }
        
        public static string ProductActivity_ProductActivityType {
            get {
                return ResourceManager.GetString("ProductActivity_ProductActivityType", resourceCulture);
            }
        }
        
        public static string ProductActivity_Detail {
            get {
                return ResourceManager.GetString("ProductActivity_Detail", resourceCulture);
            }
        }
        
        public static string ProductCategory_Name {
            get {
                return ResourceManager.GetString("ProductCategory_Name", resourceCulture);
            }
        }
        
        public static string WorkloadItem_CreatedOn {
            get {
                return ResourceManager.GetString("WorkloadItem_CreatedOn", resourceCulture);
            }
        }
        
        public static string WorkloadItem_IsProcessed {
            get {
                return ResourceManager.GetString("WorkloadItem_IsProcessed", resourceCulture);
            }
        }
        
        public static string WorkloadItem_Message {
            get {
                return ResourceManager.GetString("WorkloadItem_Message", resourceCulture);
            }
        }
    }
}
